### ISSUE TITLE
how to reduce dynamicity?

### ISSUE THREAD

**Issue by 8414sys** [damo-vilab/i2vgen-xl#27]
My inputs consist of pictures of people.
Result contain melting people.
I think it's because hyperparameters related with dynamicity is too high.
How can i reduce dynamicity?

**Comment by Steven-SWZhang** [comment]
Sorry, this version of the model does not have the ability to control the intensity of the movement, so there may be cases of failure in the generated results due to the diversity of the model. You may try modifying the seed. Additionally, there is still some difficulty in generating high-quality videos of distant human bodies, which is also a problem we are currently working on.

**Comment by Steven-SWZhang** [comment]
In addition, you can also adjust the generated results by modifying the text input. Our results have also shown that the input text is important for improving the quality of the generated video.
